databases:
  - name: kanpo-db
    plan: free
    region: oregon
    postgresMajorVersion: 16

services:
  - type: web
    name: kanpo
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: kanpo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kanpo-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: kanpo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: kanpo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kanpo-db
          property: password
