spring.application.name=kanpo
spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/kanpo}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:${DATABASE_USERNAME:postgres}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:${DATABASE_PASSWORD:hs0512}}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
