spring.application.name=kanpo
spring.datasource.url=jdbc:postgresql://localhost:5432/kanpo
spring.datasource.username=postgres
spring.datasource.password=hs0512
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
