spring.application.name=kanpo
<<<<<<< HEAD
spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/kanpo}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:${DATABASE_USERNAME:postgres}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:${DATABASE_PASSWORD:hs0512}}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
=======
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kanpo}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:hs0512}
spring.datasource.driver-class-name=org.postgresql.Driver
>>>>>>> 1a89a83e026a4a86e1ebeaf3160fb770d4a16428
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
